FROM maven:3.8.5-openjdk-17-slim AS build

WORKDIR /app

# Copy source code
COPY . .

# Package the application
RUN mvn clean package -DskipTests

# Use JDK image to run the app
FROM openjdk:17-jdk-slim

WORKDIR /app

COPY --from=build /app/target/*.jar app.jar

EXPOSE 8081

ENTRYPOINT ["java", "-jar", "app.jar"]
